"""Unity V2 bridge adapter: wire protocol, frame conversion and the RobotHardwareInterface client."""

from conrad.adapters.unity.conversion import ADAPTER_NAME, AdapterReason, PayloadStore, UnityBridgeConfig
from conrad.adapters.unity.frames import (
    DEFAULT_MAPPER,
    UNITY_FRAME_CONVENTION,
    UNITY_WORLD,
    UnityFrameMapper,
)
from conrad.adapters.unity.hardware import BridgeState, UnityRobotHardware
from conrad.adapters.unity.protocol import (
    PROTOCOL_VERSION,
    CommandPacket,
    FaultAck,
    FaultInjectionRequest,
    FaultType,
    HandshakeAck,
    HandshakeRequest,
    MessageKind,
    SensorPacket,
    SimulationValidityLevel,
    StatePacket,
    StepRequest,
    UnityProtocolError,
    WireCommandAck,
    decode_message,
    encode_message,
    make_sensor_packet,
)
from conrad.adapters.unity.transport import (
    BridgeTransport,
    RecordingTransport,
    ReplayDivergenceError,
    ReplayTransport,
    UnityBridgeError,
    UnityBridgeTimeout,
    UnityPeerError,
    ZmqBridgeTransport,
    validate_private_endpoint,
)

IMPLEMENTATION_METADATA = {
    "implementation_status": "EXPERIMENTAL_CANDIDATE",
    "source_sections": [
        "ch20 Unity external interface",
        "ch20 Technology bridge",
        "ch20 Physical software swap",
        "ch21 Same RobotHardwareInterface",
        "ch21 Python interface",
        "ch28 frame contract tests",
        "ch34 Network",
    ],
    "configuration_keys": [
        "sim.unity.bridge.control_endpoint",
        "sim.unity.bridge.stream_endpoint",
        "sim.unity.bridge.allowed_peers",
        "sim.unity.bridge.allowed_simulator_ids",
        "sim.unity.bridge.clock_domain",
        "sim.unity.bridge.lock_step",
        "sim.unity.bridge.request_timeout_ms",
        "sim.unity.bridge.require_safety_authorization",
        "sim.unity.bridge.minimum_validity_level",
    ],
    "assumptions": [
        "Conrad simulation WORLD/ROBOT: right-handed, +X forward, +Y left, +Z up (FrameConvention default)",
        "Unity: left-handed, +X right, +Y up, +Z forward; wire spatial values are Unity-convention",
        "ZeroMQ REQ/REP + PUB with JSON envelopes is the first transport; protocol is transport independent",
        "the Unity player itself has not been executed in this environment (external blocker)",
    ],
    "baselines": ["conrad.sim.kernel SimRobotHardware behind the same RobotHardwareInterface"],
    "acceptance_tests": [
        "tests/contract/unity",
        "tests/unit/adapters/unity",
    ],
    "claim_status": "IMPLEMENTED",
}

__all__ = [
    "ADAPTER_NAME",
    "DEFAULT_MAPPER",
    "IMPLEMENTATION_METADATA",
    "PROTOCOL_VERSION",
    "UNITY_FRAME_CONVENTION",
    "UNITY_WORLD",
    "AdapterReason",
    "BridgeState",
    "BridgeTransport",
    "CommandPacket",
    "FaultAck",
    "FaultInjectionRequest",
    "FaultType",
    "HandshakeAck",
    "HandshakeRequest",
    "MessageKind",
    "PayloadStore",
    "RecordingTransport",
    "ReplayDivergenceError",
    "ReplayTransport",
    "SensorPacket",
    "SimulationValidityLevel",
    "StatePacket",
    "StepRequest",
    "UnityBridgeConfig",
    "UnityBridgeError",
    "UnityBridgeTimeout",
    "UnityFrameMapper",
    "UnityPeerError",
    "UnityProtocolError",
    "UnityRobotHardware",
    "WireCommandAck",
    "ZmqBridgeTransport",
    "decode_message",
    "encode_message",
    "make_sensor_packet",
    "validate_private_endpoint",
]
