"""Generate the requirements ledger (markdown + JSON) from docs/specification/requirements_source.psv.

Status is DERIVED from the repository, never typed by hand, unless the source row carries an explicit
override (INTEGRATED / EVALUATED / VALIDATED / BLOCKED_EXTERNAL / BLOCKED_OPEN_DECISION):

  MISSING      no implementation path exists
  PARTIAL      some implementation paths exist
  IMPLEMENTED  all implementation paths exist, no test path exists
  TESTED       all implementation paths and at least one test path exist
Overrides INTEGRATED/EVALUATED/VALIDATED are downgraded to the derived status when a path is missing.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "docs" / "specification" / "requirements_source.psv"
OUT_MD = ROOT / "docs" / "specification" / "CONRAD_V2_REQUIREMENTS_LEDGER.md"
OUT_JSON = ROOT / "artifacts" / "spec" / "requirements-ledger.json"
BLOCKED = {"BLOCKED_EXTERNAL", "BLOCKED_OPEN_DECISION"}
PROMOTED = {"INTEGRATED", "EVALUATED", "VALIDATED"}
ORDER = ["MISSING", "PARTIAL", "IMPLEMENTED", "TESTED", "INTEGRATED", "EVALUATED", "VALIDATED", "BLOCKED_EXTERNAL", "BLOCKED_OPEN_DECISION"]


def _split(cell: str) -> list[str]:
    return [p.strip() for p in cell.split(";") if p.strip()]


def _exists(rel: str) -> bool:
    p = ROOT / rel
    if p.is_dir():
        return any(p.rglob("*.py")) or any(p.rglob("*.cs")) or any(p.iterdir())
    return p.exists()


def parse() -> list[dict[str, object]]:
    rows = []
    for raw in SOURCE.read_text(encoding="utf-8").splitlines():
        if not raw.strip() or raw.lstrip().startswith("#"):
            continue
        cells = [c.strip() for c in raw.split("|")]
        cells += [""] * (11 - len(cells))
        rid, section, authority, owner, summary, impl, tests, exps, keys, ext, override = cells[:11]
        impl_paths, test_paths = _split(impl), _split(tests)
        present = [p for p in impl_paths if _exists(p)]
        tests_present = [p for p in test_paths if _exists(p)]
        if not present:
            derived = "MISSING"
        elif len(present) < len(impl_paths):
            derived = "PARTIAL"
        elif not tests_present:
            derived = "IMPLEMENTED"
        else:
            derived = "TESTED"
        if override in BLOCKED:
            status = override
        elif override in PROMOTED and derived == "TESTED":
            status = override
        else:
            status = derived
        rows.append(
            {
                "requirement_id": rid,
                "source_section": section,
                "requirement_summary": summary,
                "authority": authority,
                "owner": owner,
                "implementation_status": status,
                "implementation_paths": impl_paths,
                "missing_paths": [p for p in impl_paths if p not in present],
                "test_ids": test_paths,
                "missing_tests": [p for p in test_paths if p not in tests_present],
                "experiment_ids": _split(exps),
                "configuration_keys": _split(keys),
                "assumptions": [],
                "external_dependencies": [ext] if ext else [],
                "evidence_artifacts": [],
                "maturity_level": None,
                "claim_status": "NONE" if status in ("MISSING", "PARTIAL") else "IMPLEMENTED",
            }
        )
    return rows


def main() -> int:
    rows = parse()
    ids = [r["requirement_id"] for r in rows]
    if len(ids) != len(set(ids)):
        print("duplicate requirement ids", file=sys.stderr)
        return 1
    OUT_JSON.parent.mkdir(parents=True, exist_ok=True)
    OUT_JSON.write_text(json.dumps({"source": str(SOURCE.relative_to(ROOT)), "requirements": rows}, indent=2) + "\n", encoding="utf-8")
    counts = {s: sum(1 for r in rows if r["implementation_status"] == s) for s in ORDER}
    lines = [
        "# Conrad V2 requirements ledger",
        "",
        "Generated by `scripts/build_requirements_ledger.py` from `docs/specification/requirements_source.psv`.",
        "Statuses are derived from the files present in the repository; do not edit this file by hand.",
        "",
        "| status | count |",
        "|---|---|",
        *[f"| {s} | {c} |" for s, c in counts.items() if c],
        "",
        "| ID | Source | Authority | Status | Summary | Missing |",
        "|---|---|---|---|---|---|",
    ]
    for r in rows:
        missing = ", ".join(r["missing_paths"] + r["missing_tests"]) or ""  # type: ignore[operator]
        lines.append(
            f"| {r['requirement_id']} | {r['source_section']} | {r['authority']} | {r['implementation_status']} | {r['requirement_summary']} | {missing} |"
        )
    OUT_MD.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(json.dumps(counts))
    return 0


if __name__ == "__main__":
    sys.exit(main())
